// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdgdxeodfhhvjryxfftu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkZ2R4ZW9kZmhodmpyeXhmZnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzgzNjgsImV4cCI6MjA2OTcxNDM2OH0.ibP_qKT471FSJAaEsw2CnBUOpvm7JkBXwPzvgSZEKS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});